export enum UserRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  CONTRIBUTOR = 'CONTRIBUTOR',
  REGULAR_USER = 'REGULAR_USER',
  NEW_USER = 'NEW_USER',
  BANNED_USER = 'BANNED_USER',
  BOT = 'BOT',
  MUTED_USER = 'MUTED_USER',
}
